apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: linksy
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
  # Keycloak Configuration
  KEYCLOAK_CLIENT_SECRET: "cm1HHBfKeFAzCsfGEfUCtkSamTbf9JDX"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  # Add other sensitive backend variables here
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin123"
