apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: linksy
spec:
  selector:
    matchLabels:
      app: pgadmin
      deployment: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
        deployment: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: pgadmin-config
            - secretRef:
                name: pgadmin-secrets
          volumeMounts:
            - name: pgadmin-storage
              mountPath: /var/lib/pgadmin
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
      restartPolicy: Always
      volumes:
        - name: pgadmin-storage
          persistentVolumeClaim:
            claimName: pgadmin-pvc