apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: linksy
data:
  KEYCLOAK_ADMIN: "admin"
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
  KC_DB_USERNAME: "postgres"
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HEALTH_ENABLED: "true"
  KC_HTTP_ENABLED: "true"
